### ISSUE TITLE
Stylify tunning

### ISSUE THREAD

**Issue by Machy8** [Duarte0903/fsuminho#9]
Hi, 

I have come across your cool project on Github and checked out the code and realised that you are using Stylify :). 

I have found, that you are using pure CSS for example for repeating classes like `member`  class in `members_grid.css`. 

You can simplify your work by using [components](https://stylifycss.com/docs/get-started#defining-a-component). They will be generated only when found on the page. For example for `member` class https://codepen.io/Machy8/pen/LYrdOwq?editors=1010

Components can be defined in a file when they are used within a comment (in your case HTML comment) or in a global config. The global config, if they are used across application..

If you move the config into an external file like `stylify-config.js`, then link it like `<script src="/js/stylify-config.js"></script>` you have components in one place, the CSS files can be mostly removed and the CSS will be even smaller :).

I hope this helps 🤘.

**Comment by Duarte0903** [comment]
Hi @Machy8,

When it comes to the members class, for now, I rater stick with pure css. 

However, I'm still gonna use our idea. It helps a bit in creating containers for grids like the ones you see where the member cards are displayed.

**Comment by Machy8** [comment]
Hi, not a problem :). I just was not sure if you have found the feature in the docs. 

When the project is ready, send it to the showcase in Stylify Discord to the `showcase` channel. I will make a page where the project will be displayed with a link to it :).
